server:
  port: 9090
spring:
  profiles:
      active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.model
  #逻辑删除
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: false
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: false
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0


localPicture:
 filePath: /Users/wangping/Pictures/
 localImgPath: http://192.168.10.37:${server.port}/getPicFromLocal
 path: /Users/wangping/Pictures/



